//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSGeneraConstanciasPDF {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WSGeneraConstanciasPDF.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Numero_Identificacion,
        ///       Curp,
        ///       Nombre_Completo,
        ///       Nombres,
        ///       Primer_Apellido,
        ///       Segundo_Apellido,
        ///       Fecha_De_Nacimiento,
        ///       &apos;&apos; AS Fecha_Nacimiento_Conjug,
        ///       &apos;&apos; AS Numero_Ident_Conjugue,
        ///       &apos;&apos; AS Nombre_Conjugue,
        ///       &apos;&apos; AS Primer_Apellido_Conjug,
        ///       &apos;&apos; AS Segundo_Apellido_Conjug
        ///FROM   AbT_Mg_Clientes
        ///WHERE  Codigo_Cliente = (SELECT Codigo_Cliente
        ///                         FROM   AbT_Pr_Prestamos
        ///                         WHERE  Numero_P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Constancias_DatosDeClienteXPrestamo {
            get {
                return ResourceManager.GetString("Constancias_DatosDeClienteXPrestamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Nombre_Completo,
        ///       Nombres,
        ///       Primer_Apellido,
        ///       Segundo_Apellido,
        ///       Numero_Identificacion,
        ///       Curp
        ///FROM   AbT_Mg_Clientes
        ///WHERE  Codigo_Cliente = (SELECT Codigo_Cliente
        ///                         FROM   AbT_Pr_Contratos_X_Cliente Cxc
        ///                         WHERE  Cxc.Numero_Contrato = @Numero_Prestamo
        ///                                AND Cxc.Clase_De_Cliente = &apos;C&apos;).
        /// </summary>
        internal static string Constancias_DatosDeCoacreditadoXPrestamo {
            get {
                return ResourceManager.GetString("Constancias_DatosDeCoacreditadoXPrestamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT B.Nomenclatura,
        ///       E.Descripcion AS Codigo_Barrio,
        ///       D.Nombre      AS Nombre_Mun,
        ///       C.Descripcion,
        ///       A.Nombre      AS Nombre_Dep,
        ///       B.Codigo_Postal
        ///FROM   AbC_Mg_Departamentos A,
        ///       AbT_Mg_Direcciones B,
        ///       AbC_Mg_Sectores C,
        ///       AbC_Mg_Municipios D,
        ///       AbC_Mg_Barrios_Colonia E
        ///WHERE  A.Codigo_Departamento = B.Codigo_Departamento
        ///       AND A.Codigo_Pais = B.Codigo_Pais
        ///       AND C.Codigo_Sector = B.Codigo_Sector
        ///       AND C.Codigo_Municipio = B. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Constancias_DatosDeGarantiaXPrestamo {
            get {
                return ResourceManager.GetString("Constancias_DatosDeGarantiaXPrestamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT B.Nomenclatura,
        ///       E.Descripcion AS Codigo_Barrio,
        ///       D.Nombre      AS Nombre_Mun,
        ///       C.Descripcion,
        ///       A.Nombre      AS Nombre_Dep,
        ///       B.Codigo_Postal
        ///FROM   AbC_Mg_Departamentos A,
        ///       AbT_Mg_Direcciones B,
        ///       AbC_Mg_Sectores C,
        ///       AbC_Mg_Municipios D,
        ///       AbC_Mg_Barrios_Colonia E
        ///WHERE  A.Codigo_Departamento = B.Codigo_Departamento
        ///       AND A.Codigo_Pais = B.Codigo_Pais
        ///       AND C.Codigo_Sector = B.Codigo_Sector
        ///       AND C.Codigo_Municipio = B. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Constancias_DatosDeGarantiaXPrestamoXCoacreditado {
            get {
                return ResourceManager.GetString("Constancias_DatosDeGarantiaXPrestamoXCoacreditado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT C.Ubicacion_Fisica,
        ///       G.Descripcion AS Colonia,
        ///       E.Descripcion AS Nombre_Sector,
        ///       F.Nombre      AS Municipio,
        ///       D.Nombre      AS Estado,
        ///       G.Codigo_Postal,
        ///       A.Estado      AS Estado_Prestamo
        ///FROM   AbT_Pr_Prestamos A,
        ///       AbT_Ga_Historico_Grados B,
        ///       AbT_Ga_Garantias C,
        ///       AbC_Mg_Departamentos D,
        ///       AbC_Mg_Sectores E,
        ///       AbC_Mg_Municipios F,
        ///       AbC_Mg_Barrios_Colonia G,
        ///       AbT_Mg_Clientes H
        ///WHERE  A.Codigo_Agencia = B.Codigo_A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Constancias_DireccionGarantiaXPrestamo {
            get {
                return ResourceManager.GetString("Constancias_DireccionGarantiaXPrestamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///FROM   AbC_Empresas_Constancias
        ///WHERE  Siglas_Emp = @sBaseJit.
        /// </summary>
        internal static string Constancias_EmpresasSiglasEmp {
            get {
                return ResourceManager.GetString("Constancias_EmpresasSiglasEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * 
        ///FROM   AbT_Hsc_constancias@@Anno_v3
        ///WHERE  Numero_Prestamo = @Numero_Prestamo
        ///       AND Codigo_SusDeu &lt;&gt; 0
        ///       AND Imprimir = &apos;S&apos;.
        /// </summary>
        internal static string Constancias_HSCConstancias {
            get {
                return ResourceManager.GetString("Constancias_HSCConstancias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Error
        ///FROM   AbT_Hsc_constancias@@Anno_v3
        ///WHERE  Numero_Prestamo = @Numero_Prestamo.
        /// </summary>
        internal static string Constancias_HSCConstancias_Error {
            get {
                return ResourceManager.GetString("Constancias_HSCConstancias_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &apos;&apos; Error
        ///FROM   AbT_Hsc_constancias@@Anno_v3
        ///WHERE  Numero_Prestamo = @Numero_Prestamo.
        /// </summary>
        internal static string Constancias_HSCConstancias2_Error {
            get {
                return ResourceManager.GetString("Constancias_HSCConstancias2_Error", resourceCulture);
            }
        }
    }
}
